package components

import (
	"github.com/nobonobo/spago"
)

// Render ...
func (c *Header) Render() spago.HTML {
	return spago.Tag("header", 		
		spago.A("class", spago.S(`navbar`)),
		spago.A("role", spago.S(`navigation`)),
		spago.A("aria-label", spago.S(`main navigation`)),
		spago.Tag("div", 			
			spago.A("class", spago.S(`container`)),
			spago.Tag("div", 				
				spago.A("class", spago.S(`navbar-brand`)),
				spago.Tag("a", 					
					spago.A("class", spago.S(`navbar-item`)),
					spago.A("href", spago.S(`#`)),
					spago.Tag("span", 						
						spago.A("class", spago.S(`icon-text`)),
						spago.Tag("span", 							
							spago.A("class", spago.S(`icon`)),
							spago.Tag("i", 								
								spago.A("class", spago.S(`fas fa-home`)),
							),
						),
						spago.Tag("span", 							
							spago.A("class", spago.S(`has-text-weight-semibold`)),
							spago.T(`Spago`),
						),
					),
				),
				spago.Tag("a", 					
					spago.A("role", spago.S(`button`)),
					spago.A("class", spago.S(`navbar-burger`)),
					spago.A("aria-label", spago.S(`menu`)),
					spago.A("aria-expanded", spago.S(`false`)),
					spago.Tag("span", 						
						spago.A("aria-hidden", spago.S(`true`)),
					),
					spago.Tag("span", 						
						spago.A("aria-hidden", spago.S(`true`)),
					),
					spago.Tag("span", 						
						spago.A("aria-hidden", spago.S(`true`)),
					),
				),
			),
			spago.Tag("div", 				
				spago.A("id", spago.S(`navbarMenuHero`)),
				spago.A("class", spago.S(`navbar-menu`)),
				spago.Tag("div", 					
					spago.A("class", spago.S(`navbar-start`)),
					spago.Tag("a", 						
						spago.A("class", spago.S(`navbar-item`)),
						spago.T(`Home`),
					),
					spago.Tag("a", 						
						spago.A("class", spago.S(`navbar-item`)),
						spago.T(`Documentation`),
					),
				),
			),
		),
	)
}
