package components

import (
	"github.com/nobonobo/spago"
)

// Render ...
func (c *Header) Render() spago.HTML {
	return spago.Tag("header", 		
		spago.A("class", spago.S(`navbar`)),
		spago.A("role", spago.S(`navigation`)),
		spago.A("aria-label", spago.S(`main navigation`)),
		spago.Tag("div", 			
			spago.A("class", spago.S(`container`)),
			spago.Tag("div", 				
				spago.A("class", spago.S(`navbar-brand`)),
				spago.Tag("a", 					
					spago.A("class", spago.S(`navbar-item`)),
					spago.A("href", spago.S(`#`)),
					spago.Tag("span", 						
						spago.A("class", spago.S(`icon-text`)),
						spago.Tag("span", 							
							spago.A("class", spago.S(`icon`)),
							spago.Tag("i", 								
								spago.A("class", spago.S(`fas fa-home`)),
							),
						),
						spago.Tag("span", 							
							spago.A("class", spago.S(`has-text-weight-semibold`)),
							spago.T(`MMD three.js`),
						),
					),
				),
				spago.Tag("a", 					
					spago.A("role", spago.S(`button`)),
					spago.A("class", spago.S(`navbar-burger`)),
					spago.A("aria-label", spago.S(`menu`)),
					spago.A("aria-expanded", spago.S(`false`)),
					spago.Event("click", c.toggleMenu),
					spago.Tag("span", 						
						spago.A("aria-hidden", spago.S(`true`)),
					),
					spago.Tag("span", 						
						spago.A("aria-hidden", spago.S(`true`)),
					),
					spago.Tag("span", 						
						spago.A("aria-hidden", spago.S(`true`)),
					),
				),
			),
			spago.Tag("div", 				
				spago.A("id", spago.S(`navbarMenuHero`)),
				spago.A("class", spago.S(`navbar-menu `, spago.S(c.isActive), ``)),
				spago.Tag("div", 					
					spago.A("class", spago.S(`navbar-start`)),
				),
				spago.Tag("div", 					
					spago.A("class", spago.S(`navbar-end`)),
					spago.Tag("div", 						
						spago.A("class", spago.S(`navbar-item has-dropdown is-hoverable`)),
						spago.Tag("a", 							
							spago.A("class", spago.S(`navbar-link`)),
							spago.T(`Model`),
						),
						spago.Tag("div", 							
							spago.A("class", spago.S(`navbar-dropdown`)),
							spago.Tag("a", 								
								spago.A("class", spago.S(`navbar-item`)),
								spago.Event("click", c.changeModelToDiluc),
								spago.T(`Diluc`),
							),
							spago.Tag("a", 								
								spago.A("class", spago.S(`navbar-item`)),
								spago.Event("click", c.changeModelToLisa),
								spago.T(`Lisa`),
							),
							spago.Tag("a", 								
								spago.A("class", spago.S(`navbar-item`)),
								spago.Event("click", c.changeModelToMiku),
								spago.T(`Miku`),
							),
						),
					),
					spago.Tag("div", 						
						spago.A("class", spago.S(`navbar-item has-dropdown is-hoverable`)),
						spago.Tag("a", 							
							spago.A("class", spago.S(`navbar-link`)),
							spago.T(`Motion`),
						),
						spago.Tag("div", 							
							spago.A("class", spago.S(`navbar-dropdown`)),
							spago.Tag("a", 								
								spago.A("class", spago.S(`navbar-item`)),
								spago.Event("click", c.changeMotionToDance1),
								spago.T(`Dance1`),
							),
							spago.Tag("a", 								
								spago.A("class", spago.S(`navbar-item`)),
								spago.Event("click", c.changeMotionToDance2),
								spago.T(`Dance2`),
							),
							spago.Tag("a", 								
								spago.A("class", spago.S(`navbar-item`)),
								spago.Event("click", c.changeMotionToDance3),
								spago.T(`Dance3`),
							),
						),
					),
				),
			),
		),
	)
}
